version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-node-browsers
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Instalando dependencias
          command: |
            sudo pip install pipenv==11.6.0
            pipenv install
            pipenv run "python manage.py test -v 2"
  deploy:
    docker:
      - image: circleci/python:3.6.5-node-browsers
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: echo -e "Host hugoruscitti.com.ar\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: git remote add dokku dokku@hugoruscitti.com.ar:pilas-engine-backend
      - run: git push dokku master:master
workflows:
  version: 2
  compilar-y-subir:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /^v\d+.\d+.\d+/
            branches:
              ignore: /.*/
