# Generated by Django 2.0.6 on 2019-07-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='codigo_serializado',
            field=models.TextField(default=''),
        ),
    ]
