# Generated by Django 2.0.6 on 2019-07-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0003_auto_20190702_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
