# Generated by Django 2.2.2 on 2020-11-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0005_proyecto_ver_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='codigo',
        ),
    ]
