# Generated by Django 2.2.2 on 2021-03-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0006_remove_proyecto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(default=None, null=True, upload_to='proyectos/'),
        ),
    ]
