# Generated by Django 2.2.2 on 2021-03-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0007_proyecto_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='codigo_serializado',
        ),
    ]
