# Generated by Django 2.2.2 on 2021-03-11 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0008_remove_proyecto_codigo_serializado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre',
        ),
    ]
