# Generated by Django 2.2.2 on 2021-03-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0009_remove_proyecto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
