# Generated by Django 2.2.2 on 2021-03-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0010_proyecto_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.FileField(default=None, null=True, upload_to='imagenes/'),
        ),
    ]
