# Generated by Django 3.1.14 on 2021-12-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0012_proyecto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=128)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'tags',
                'db_table': 'tags',
                'ordering': ['-id'],
            },
        ),
    ]
