# Generated by Django 3.1.14 on 2021-12-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0013_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tags',
            field=models.ManyToManyField(related_name='proyectos', to='pilas.Tag'),
        ),
    ]
