# Generated by Django 3.1.14 on 2021-12-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0014_proyecto_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=256),
        ),
    ]
