# Generated by Django 3.1.14 on 2022-02-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilas', '0015_proyecto_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
